// Call queue validations
exports.callQueueValidations = {
    add_to_callerid: 'required|max:100',
    announce_holdtime: 'max:100',
    announce_position: 'max:100',
    announce_round_seconds: 'max:100',
    autofill: 'max:100',
    autopause: 'max:100',
    calls_limit: 'required|max:32',
    conversion_l1: 'max:2|type:numeric',
    conversion_l2: 'max:2|type:numeric',
    conversion_l3: 'max:2|type:numeric',
    defaultrule: 'max:100',
    efficacy_l1: 'max:2|type:numeric',
    efficacy_l2: 'max:2|type:numeric',
    efficacy_l3: 'max:2|type:numeric',
    eventmemberstatus: 'max:100',
    eventwhencalled: 'max:100',
    flowout: 'required|max:32',
    crm: 'max:100',
    has_transfer: 'max:100',
    joinempty: 'max:100',
    leavewhenempty: 'max:100',
    maxlen: 'max:32|type:numeric',
    memberdelay: 'max:32|type:numeric',
    membersmacro: 'max:100',
    mode_recording: 'max:100',
    monitor_type: 'max:100',
    musicclass: 'required|max:100',
    name: 'required|min:2|max:32|type:alphaNumericDash',
    payment_methods_id: 'max:100',
    polls_id: 'max:100',
    reportholdtime: 'max:100',
    retry: 'required|max:32',
    setinterfacevar: 'max:100',
    setqueueentryvar: 'max:100',
    setqueuevar: 'max:100',
    strategy: 'required|max:100',
    timeout: 'required|max:32',
    timeoutrestart: 'max:100',
    weight: 'max:32|type:numeric',
    wrapuptime: 'required|max:32',
}

// Call queue result validations
exports.callQueueResultValidations = {
    abbreviation: 'required|max:2',
    color: 'required|max:12',
    description: 'max:100',
    name: 'required|min:2|max:32|type:alphaNumericDash',
}